import { Activity, AppWindow, BookOpen, ChevronRight, ClipboardCheck, Database, FileClock, FileText, Home, ListChecks, Plus, RotateCcw, Save, Search, Trash2, UserCog, Users, Waypoints } from 'lucide-react'
import { useMemo, useState } from 'react'
import type { LucideIcon } from 'lucide-react'
import { Modal } from '../components/Modal'
import { PageHeader } from '../components/PageHeader'
import { StatusBadge } from '../components/StatusBadge'
import { Button } from '../components/ui/Button'
import { dataService, type DataKey } from '../services/storage'
import { useData } from '../hooks/useData'
import type { HomeContent } from '../types'

type Field = { key: string; label: string; options?: string[]; textarea?: boolean }
type ModuleConfig = { id: string; title: string; description: string; key?: DataKey; icon: LucideIcon; columns?: Field[]; fields?: Field[]; defaults?: Record<string, unknown> }

const modules: ModuleConfig[] = [
  { id: 'apps', title: '应用管理', description: '维护应用目录、建设单位、接入状态与运行状态。', key: 'apps', icon: AppWindow, columns: [{ key: 'name', label: '应用名称' }, { key: 'organization', label: '建设单位' }, { key: 'accessStatus', label: '接入状态' }, { key: 'operationStatus', label: '运行状态' }, { key: 'updatedAt', label: '更新时间' }], fields: [{ key: 'name', label: '应用名称' }, { key: 'organization', label: '建设单位' }, { key: 'description', label: '简介', textarea: true }, { key: 'category', label: '应用类型' }, { key: 'accessStatus', label: '接入状态', options: ['已接入', '云端已部署', '技术对接中', '待上云', '规划接入'] }, { key: 'operationStatus', label: '运行状态', options: ['业务运营中', '联调中', '待上云', '未运行'] }, { key: 'deployment', label: '部署位置' }, { key: 'database', label: '数据库类型' }, { key: 'owner', label: '责任联系人' }, { key: 'updatedAt', label: '更新时间' }], defaults: { accessStatus: '规划接入', operationStatus: '未运行', deployment: '规划中', database: '待确认', updatedAt: '2026-07-16 10:00', featured: false } },
  { id: 'resources', title: '数据资源管理', description: '维护数据目录、来源、权限与更新方式。', key: 'resources', icon: Database, columns: [{ key: 'name', label: '资源名称' }, { key: 'source', label: '来源应用' }, { key: 'type', label: '类型' }, { key: 'organization', label: '责任单位' }, { key: 'updatedAt', label: '更新时间' }], fields: [{ key: 'name', label: '数据名称' }, { key: 'source', label: '来源应用' }, { key: 'type', label: '类型', options: ['结构化数据', 'CSV文件', '接口数据', '文档资料'] }, { key: 'updateMode', label: '更新方式' }, { key: 'volume', label: '数据量' }, { key: 'updatedAt', label: '更新时间' }, { key: 'organization', label: '责任单位' }, { key: 'permission', label: '权限范围' }, { key: 'description', label: '说明', textarea: true }], defaults: { type: '结构化数据', permission: '授权用户可见', updatedAt: '2026-07-16 10:00' } },
  { id: 'edges', title: '边缘节点管理', description: '维护节点建设、部署与接入台账。', key: 'edgeNodes', icon: Waypoints, columns: [{ key: 'code', label: '节点编号' }, { key: 'name', label: '节点名称' }, { key: 'organization', label: '所属单位' }, { key: 'machine', label: '关联机床' }, { key: 'status', label: '状态' }], fields: [{ key: 'code', label: '节点编号' }, { key: 'name', label: '节点名称' }, { key: 'organization', label: '所属单位' }, { key: 'machine', label: '关联机床' }, { key: 'os', label: '操作系统' }, { key: 'protocol', label: '通信协议' }, { key: 'ip', label: 'IP地址' }, { key: 'status', label: '接入状态', options: ['规划建设中', '待部署', '待接入', '在线', '异常'] }, { key: 'lastSeen', label: '最近在线时间' }, { key: 'note', label: '备注', textarea: true }], defaults: { status: '规划建设中', ip: '待分配', lastSeen: '尚未建设' } },
  { id: 'access', title: '接入申请管理', description: '审核五步接入申请并维护实施状态。', key: 'accessApplications', icon: ClipboardCheck, columns: [{ key: 'id', label: '申请编号' }, { key: 'appName', label: '应用名称' }, { key: 'organization', label: '建设单位' }, { key: 'status', label: '状态' }, { key: 'createdAt', label: '提交时间' }], fields: [{ key: 'appName', label: '应用名称' }, { key: 'organization', label: '建设单位' }, { key: 'appOwner', label: '应用负责人' }, { key: 'technicalContact', label: '技术联系人' }, { key: 'status', label: '审核状态', options: ['草稿', '待审核', '材料补充中', '实施中', '已完成', '已退回'] }, { key: 'issueLog', label: '问题记录', textarea: true }], defaults: { status: '待审核', createdAt: '2026-07-16 10:00' } },
  { id: 'users', title: '用户与角色管理', description: '管理平台用户、所属单位与角色权限。', key: 'users', icon: Users, columns: [{ key: 'name', label: '姓名' }, { key: 'organization', label: '所属单位' }, { key: 'role', label: '角色' }, { key: 'status', label: '状态' }, { key: 'lastLogin', label: '最近登录' }], fields: [{ key: 'name', label: '姓名' }, { key: 'organization', label: '所属单位' }, { key: 'role', label: '角色', options: ['平台管理员', '应用负责人', '接入联系人', '普通用户'] }, { key: 'status', label: '状态', options: ['启用', '停用'] }, { key: 'lastLogin', label: '最近登录' }], defaults: { role: '普通用户', status: '启用', lastLogin: '尚未登录' } },
  { id: 'home', title: '首页内容管理', description: '维护首页主标题、说明和平台公告。', icon: Home },
  { id: 'statuses', title: '状态标签管理', description: '查看统一状态规范，并维护监测台账状态。', key: 'monitors', icon: ListChecks, columns: [{ key: 'appName', label: '应用名称' }, { key: 'serviceStatus', label: '服务状态' }, { key: 'databaseStatus', label: '数据库状态' }, { key: 'apiStatus', label: '接口状态' }, { key: 'version', label: '版本' }], fields: [{ key: 'appName', label: '应用名称' }, { key: 'serviceStatus', label: '服务状态', options: ['正常', '联调中', '异常', '未接入', '待检查'] }, { key: 'databaseStatus', label: '数据库状态', options: ['正常', '联调中', '异常', '未接入', '待检查'] }, { key: 'apiStatus', label: '接口状态', options: ['正常', '联调中', '异常', '未接入', '待检查'] }, { key: 'lastAccess', label: '最近访问时间' }, { key: 'version', label: '当前版本' }], defaults: { serviceStatus: '待检查', databaseStatus: '待检查', apiStatus: '待检查', version: '待确认', lastAccess: '尚未检查' } },
  { id: 'docs', title: '文档管理', description: '维护帮助中心的规范、指南与说明。', key: 'documents', icon: BookOpen, columns: [{ key: 'title', label: '文档标题' }, { key: 'category', label: '分类' }, { key: 'updatedAt', label: '更新时间' }, { key: 'description', label: '摘要' }], fields: [{ key: 'title', label: '文档标题' }, { key: 'category', label: '分类' }, { key: 'updatedAt', label: '更新时间' }, { key: 'description', label: '摘要', textarea: true }], defaults: { category: '平台说明', updatedAt: '2026-07-16' } },
  { id: 'logs', title: '操作日志', description: '记录本地演示环境中的关键维护操作。', icon: FileClock },
]

function GenericManager({ config, onLog }: { config: ModuleConfig; onLog: (text: string) => void }) {
  const { data } = useData<Record<string, any>[]>(config.key!)
  const [search, setSearch] = useState('')
  const [editing, setEditing] = useState<Record<string, any> | null>(null)
  const filtered = useMemo(() => data.filter((row) => JSON.stringify(row).toLowerCase().includes(search.toLowerCase())), [data, search])
  const save = () => { if (!editing) return; const record: Record<string, any> = { ...config.defaults, ...editing, id: editing.id || `${config.id}-${Date.now()}` }; dataService.upsert(config.key as any, record); onLog(`${editing.id ? '编辑' : '新增'}：${record.name || record.title || record.appName || record.id}`); setEditing(null) }
  const remove = (row: Record<string, any>) => { if (!window.confirm(`确定删除“${row.name || row.title || row.appName || row.id}”吗？`)) return; dataService.remove(config.key as any, row.id); onLog(`删除：${row.name || row.title || row.appName || row.id}`) }
  return <div className="min-w-0"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><label className="relative w-full max-w-80"><Search className="absolute left-3.5 top-3.5 text-muted" size={16} /><input className="input pl-10" placeholder="搜索当前模块" value={search} onChange={(event) => setSearch(event.target.value)} /></label><Button icon={<Plus size={16} />} onClick={() => setEditing({ ...config.defaults })}>新增记录</Button></div><div className="thin-scrollbar overflow-x-auto rounded-2xl border border-line"><table className="min-w-[860px] w-full"><thead className="table-head"><tr>{config.columns?.map((column) => <th className="px-4 py-3.5" key={column.key}>{column.label}</th>)}<th className="px-4 py-3.5 text-right">操作</th></tr></thead><tbody>{filtered.map((row) => <tr key={row.id}>{config.columns?.map((column) => <td className="table-cell max-w-xs truncate" key={column.key}>{column.key.toLowerCase().includes('status') ? <StatusBadge status={String(row[column.key] ?? '未设置')} /> : String(row[column.key] ?? '—')}</td>)}<td className="table-cell"><div className="flex justify-end gap-1"><Button variant="ghost" className="h-8 px-3" onClick={() => setEditing({ ...row })}>编辑</Button><Button variant="danger" className="h-8 px-3" onClick={() => remove(row)}><Trash2 size={14} /></Button></div></td></tr>)}</tbody></table>{!filtered.length && <div className="p-10 text-center text-sm text-muted">暂无记录，可点击“新增记录”开始维护。</div>}</div><Modal open={!!editing} onClose={() => setEditing(null)} title={`${editing?.id ? '编辑' : '新增'}${config.title}`} description="保存后将立即同步至对应前台页面。"><div className="grid grid-cols-2 gap-5">{config.fields?.map((field) => <label key={field.key} className={field.textarea ? 'col-span-2' : ''}><span className="label">{field.label}</span>{field.options ? <select className="input" value={String(editing?.[field.key] ?? '')} onChange={(event) => setEditing((current) => ({ ...current, [field.key]: event.target.value }))}><option value="">请选择</option>{field.options.map((option) => <option key={option}>{option}</option>)}</select> : field.textarea ? <textarea className="textarea" value={String(editing?.[field.key] ?? '')} onChange={(event) => setEditing((current) => ({ ...current, [field.key]: event.target.value }))} /> : <input className="input" value={String(editing?.[field.key] ?? '')} onChange={(event) => setEditing((current) => ({ ...current, [field.key]: event.target.value }))} />}</label>)}</div><div className="mt-6 flex justify-end gap-3"><Button variant="secondary" onClick={() => setEditing(null)}>取消</Button><Button icon={<Save size={16} />} onClick={save}>保存并同步</Button></div></Modal></div>
}

function HomeManager({ onLog }: { onLog: (text: string) => void }) {
  const { data } = useData<HomeContent>('homeContent')
  const [form, setForm] = useState(data)
  return <div className="max-w-4xl space-y-5"><label><span className="label">首页主标题</span><textarea className="textarea text-lg font-medium" value={form.heroTitle} onChange={(e) => setForm({ ...form, heroTitle: e.target.value })} /></label><label><span className="label">平台说明</span><textarea className="textarea" value={form.heroDescription} onChange={(e) => setForm({ ...form, heroDescription: e.target.value })} /></label><label><span className="label">首页公告</span><input className="input" value={form.announcement} onChange={(e) => setForm({ ...form, announcement: e.target.value })} /></label><Button icon={<Save size={16} />} onClick={() => { dataService.saveHomeContent(form); onLog('更新：首页内容') }}>保存并同步到首页</Button></div>
}

export function AdminPage() {
  const [active, setActive] = useState('apps')
  const [logs, setLogs] = useState<string[]>(() => { try { return JSON.parse(localStorage.getItem('mcep:operation-logs') ?? '[]') } catch { return [] } })
  const config = modules.find((item) => item.id === active)!
  const ConfigIcon = config.icon
  const addLog = (text: string) => { const next = [`${new Date().toLocaleString('zh-CN')} · 雅青 · ${text}`, ...logs].slice(0, 100); setLogs(next); localStorage.setItem('mcep:operation-logs', JSON.stringify(next)) }
  const reset = () => { if (window.confirm('确定恢复全部 Mock 初始数据吗？本地编辑内容将被清除。')) { dataService.reset(); addLog('恢复全部 Mock 初始数据') } }
  return <div className="page-shell py-8 lg:py-10"><PageHeader eyebrow="演示管理端" title="平台内容与台账管理" description="当前为本地演示数据管理，所有编辑结果保存在浏览器 localStorage 中，并同步到前台页面；未接入正式后端。" actions={<Button variant="secondary" icon={<RotateCcw size={16} />} onClick={reset}>恢复初始数据</Button>} /><div className="grid min-w-0 grid-cols-[210px_minmax(0,1fr)] gap-4 xl:grid-cols-[240px_minmax(0,1fr)] xl:gap-5 2xl:grid-cols-[270px_minmax(0,1fr)] 2xl:gap-6"><aside className="card h-fit p-2 xl:p-3"><div className="mb-2 flex items-center gap-3 border-b border-line px-2 py-4 xl:px-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-brand text-white xl:h-10 xl:w-10"><UserCog size={20} /></span><div className="min-w-0"><p className="truncate font-semibold text-ink">演示管理端</p><p className="mt-0.5 truncate text-xs text-muted">平台管理员 · 雅青</p></div></div>{modules.map(({ id, title, icon: Icon }) => <button key={id} onClick={() => setActive(id)} className={`focus-ring flex w-full items-center gap-2 rounded-xl px-2 py-3 text-left text-xs transition xl:gap-3 xl:px-3 xl:text-sm ${active === id ? 'bg-brand text-white' : 'text-muted hover:bg-canvas hover:text-ink'}`}><Icon size={17} className="shrink-0" /><span className="min-w-0 flex-1 truncate">{title}</span><ChevronRight size={15} className={`shrink-0 ${active === id ? 'text-white/70' : 'text-line'}`} /></button>)}</aside><section className="card min-w-0 min-h-[680px] p-5 xl:p-7"><div className="mb-7 flex flex-wrap items-start justify-between gap-3 border-b border-line pb-5"><div><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-brand/10 text-brand"><ConfigIcon size={20} /></span><h2 className="text-xl font-semibold text-ink">{config.title}</h2></div><p className="mt-3 text-sm text-muted">{config.description}</p></div><span className="rounded-full bg-canvas px-3 py-1.5 text-xs text-muted">本地演示数据</span></div>{config.key && <GenericManager config={config} onLog={addLog} />}{active === 'home' && <HomeManager onLog={addLog} />}{active === 'logs' && <div><div className="mb-5 flex items-center justify-between"><p className="text-sm text-muted">共记录 {logs.length} 条本地操作</p><Button variant="danger" onClick={() => { setLogs([]); localStorage.removeItem('mcep:operation-logs') }}>清空日志</Button></div><div className="space-y-2">{logs.length ? logs.map((log, index) => <div className="flex items-center gap-3 rounded-xl border border-line px-4 py-3 text-sm" key={`${log}-${index}`}><Activity size={16} className="shrink-0 text-brand" /><span className="min-w-0 break-words">{log}</span></div>) : <div className="rounded-2xl bg-canvas p-10 text-center text-sm text-muted"><FileText className="mx-auto mb-3" />暂无本地操作记录</div>}</div></div>}</section></div></div>
}
